name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  govet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: ls
      run: ls
      
    - name: install vettool
      run: GOBIN=$(pwd) go install github.com/Sigumaa/stringdetector/cmd/stringdetector@latest
      
    - name: ls
      run: ls
