name: Go

on:
  pull_request:
    branches: [ "main" ]

jobs:

  govet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"
      
    - name: install vettool
      run: go install github.com/Sigumaa/stringdetector/cmd/stringdetector@latest
      
    - name: go vet
      run: |
        go vet -vettool=`which stringdetector` -stringdetector.flag="Url" ./... | tee result
        sed -i -z 's/\n/\\n/g' result
    
    - name: comment
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ github.event.pull_request.comments_url }}
      run: |
        curl -X POST \
        -H "Authorization: token ${GITHUB_TOKEN}" \
        -d "{\"body\": \"```\\n$(cat result)\\n```\"}" \
        ${URL}
        
